version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:ubuntu-lts
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "CHANGELOG.md" }}
      - run:
          name: 'Prepare deps'
          command: |
            sudo apt-get install -y pkg-config libssl-dev m4 libffi-dev
            opam switch 4.07
            eval $(opam env)
            opam update
            opam install -y dune
            dune external-lib-deps cli/main.exe | grep -E '^-' | cut -c 3- | tr '\n' ' ' > ./deps
            echo ./deps
            opam install -y $(cat ./deps)
      - save_cache:
          key: deps-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "CHANGELOG.md" }}
          paths:
            - '~/.opam'
      - run:
          name: 'Build'
          command: |
            opam switch 4.07
            eval $(opam env)
            dune build cli/main.exe
